# -*- coding: utf-8 -*-
"""sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IkgO5CfrAqAxU1ozWr9uxsVrKdzTzjAV
"""

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

# Load data
train_df = pd.read_csv('Training.csv')
test_df = pd.read_csv('Testing.csv')

# Initialize scikit-learn's KNN classifier
knn = KNeighborsClassifier(n_neighbors=4)

# Fit the training data to the classifier
knn.fit(train_df[['X', 'Y']], train_df['Outcome'])

# Calculate accuracy on the testing data using scikit-learn's score method
sklearn_accuracy = knn.score(test_df[['X', 'Y']], test_df['Outcome'])


print(f"Scikit-learn's KNN accuracy: {sklearn_accuracy}")